stages:
    - prepare
    - test

cache:
  paths:
    - vendor

composer:
  image: composer:1.10.15
  stage: prepare
  script:
    - composer install --optimize-autoloader --prefer-dist --no-progress

test:php7:
    stage: test
    image: php:7.4-cli
    dependencies:
        - composer
    before_script:
        - apt-get update -yqq
        - apt-get install -yqq git 
        # Install Xdebug
        - pecl install xdebug
        - docker-php-ext-enable xdebug
    only:
        - main
    script:
        - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
    tags:
        - docker
